theme: jekyll-theme-minimal
title: Sunny Yan's Data Science Portfolio
logo: "https://raw.githubusercontent.com/sunnyyan97/bigsunn97.github.io/main/1587652621092.jpg"
description: 
  My name is Sunny Yan. I’m an aspiring data scientist that is passionate about telling stories through data. My main skills are working with Python 
  and the Pydata stack (numpy, pandas, scikit-learn) for data analysis, as well as SQL and R. 
  <br><br>
  I started my Data Science Journey by completing the IBM Data Science Professional Certificate on Coursera, 
  Afterwards, I began pursuing another Data Science certificate from Dataquest to further my learning with Python and SQL. 
  <br><br>
  This website is a portfolio of the projects that I’m most proud of, featuring projects from my courses and personal projects. 
  <br><br>
  <a href="https://www.linkedin.com/in/sunny-yan-0504a6120/">View My LinkedIn Profile</a> 
