theme: jekyll-theme-minimal
title: Sunny Yan's Data Analyst Portfolio
logo: "https://raw.githubusercontent.com/sunnyyan97/sunnyyan97.github.io/main/1587652621092.jpg"
description: 
  Aspiring Data Analyst passionate about answering questions with data. My main skills are working in Python 
  and the Pydata stack(numpy, pandas, scikit-learn), SQL and Tableau for data visualization. 
  <br><br>
  I started my Data Science Journey by completing the IBM Data Science Professional Certificate on Coursera,
  and then completed the Data Analyst career path from Dataquest to further my learning through projects. 
  <br><br>
  This website is a portfolio of projects that I've done, from my coursework and my personal projects. 
  <br><br>
  <a href="https://www.linkedin.com/in/sunny-yan-0504a6120/">View My LinkedIn Profile</a> 
 
