theme: jekyll-theme-minimal
title: Sunny Yan's Data Science Portfolio
logo: "https://raw.githubusercontent.com/sunnyyan97/bigsunn97.github.io/main/1587652621092.jpg"
description: Aspiring data scientist with interests in Sports, Politics and Finance. 
