theme: jekyll-theme-minimal
title: Sunny Yan's Data Science Portfolio
description: Aspiring data scientist with interests in Sports, Politics and Finance. 
[<img src="https://raw.githubusercontent.com/bigsunn97/bigsunn97.github.io/main/1587652621092.jpg">](https://github.com/bigsunn97/Coursera_Capstone)
